### ISSUE TITLE
Support target_os

### ISSUE THREAD

**Issue by Porges** [est31/cargo-udeps#123]
It seems like `target_os` is not supported, leading to false positives.

**Comment by faern** [comment]
Maybe you mean something different than what I experience. But I get false negatives due to this. If I run `cargo udeps --all-targets` on Linux, in a crate with:

```toml
[target.'cfg(target_os="macos")'.dependencies]
an_unused_dependency = "1"
```

It will not find it. Is there any way to make `cargo udeps` check all targets. Sorry if this is not at all what the issue is about.
