### ISSUE TITLE
False positive warning on duplicate dependency

### ISSUE THREAD

**Issue by max-sixty** [est31/cargo-udeps#192]
Thanks for the excellent crate!

FYI we get a false positive on a duplicate dependency for these lines of code:

https://github.com/PRQL/prql/blob/0a6d2e881b47ec3f6c09b361da625ff252ca512e/crates/prql-parser/Cargo.toml#L22-L25

```toml
[target.'cfg(not(target_family="wasm"))'.dependencies]
chumsky = "0.9.2"
[target.'cfg(target_family="wasm")'.dependencies]
chumsky = {version = "0.9.2", features = ["ahash", "std"], default-features = false}
```

```

duplicate package mentioned in toml chumsky v0.9.2. Some("chumsky")
```

These aren't duplicated since there's no overlap in targets. 

Here's an example of the annotation: https://github.com/PRQL/prql/actions/runs/5916930046
