### ISSUE TITLE
Proper testsuite

### ISSUE THREAD

**Issue by est31** [est31/cargo-udeps#3]
It would be cool to have a proper testsuite.

**Comment by qryxip** [comment]
How about using [`assert_cmd`](https://crates.io/crates/assert_cmd)? Then we can put crates (including `Cargo.lock`) under `tests/` as testsuites like this and run `integration-test`s with `--target-dir ./target/tests/testapp` (or `$TMPDIR/cargo_udeps_tests.************/target/sampleapp`).

```
./cargo-udeps
└── tests
    ├── testapp
    │   ├── Cargo.lock
    │   ├── Cargo.toml
    │   ├── examples
    │   │   └── example.rs
    │   ├── src
    │   │   ├── lib.rs
    │   │   └── main.rs
    │   └── tests
    │       └── test.rs
    └── testapp.rs
```

```toml
[package]
name = "testapp"
version = "0.0.0"
authors = ["Ryo Yamashita <qryxip@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
failure = "0.1.5"
structopt = "0.3.2"
termcolor = "1.0.5"

[dev-dependencies]
tempdir = "0.3.7"

[build-dependencies]
failure = "0.1.5"
```
