### ISSUE TITLE
False positive when `-` in crate name

### ISSUE THREAD

**Issue by ralpha** [est31/cargo-udeps#96]
We use [`iso639-1`](https://crates.io/crates/iso639-1) in our tool.
But this is flagged as unused. This is most likely because of the `-` in the crate name.
The actual use is `iso639_1::something()`

So the `-` is replaced with a `_` in the code.
If this is a common problem maybe there can a special case for all the crates that have a `-` in there name.

For now I just added it to the ignore list:
```toml
[package.metadata.cargo-udeps.ignore]
normal = ["iso639-1"]
```
